### ISSUE TITLE
The Cargo lock file should not be commited

### ISSUE THREAD

**Issue by IvoWingelaar** [unrust/uni-app#1]
Normally libraries should not commit the lock file that Cargo produces in version control. Is there a specific reason you do include it?

**Comment by IvoWingelaar** [comment]
Probably related to this: the `.gitignore` file is also missing.

**Comment by edwin0cheng** [comment]
Yes, seem like we forget to add back the .gitignore file when we import from the unrust main repository. I will add it back tonight. Thanks for your report.

**Comment by edwin0cheng** [comment]
Fixed by #5
