### ISSUE TITLE
Upgrade to glutin 0.17.0 to prevent windows from being resizable

### ISSUE THREAD

**Issue by IvoWingelaar** [unrust/uni-app#2]
In `glutin 0.17` we can use `WindowBuilder::set_resizable(false)` to prevent certain tiling window managers (such as `bspwm`) to automatically resize the window, and push the rendered image offscreen.

This upgrade takes DPI scaling into consideration so it does require a few changes to how we request a window from `glutin`. I've already made a branch that fixes this, and will open the PR shortly.

**Comment by edwin0cheng** [comment]
#3 should fixed this.
