### ISSUE TITLE
publishing lower crates ?

### ISSUE THREAD

**Issue by jice-nospam** [unrust/uni-app#7]
I'm starting considering publishing doryen-rs. For that, I first need to publish webgl, uni-app and uni-glsl. Do you think those lower crates are crates.io worthy ? I've been using them for months in two different projects and they seem stable to me (at least for a 0.1.0 version).

**Comment by edwin0cheng** [comment]
I think it is okay to publishing these lower level crates, i would do it in this weekend 👍

**Comment by jice-nospam** [comment]
ok great. I can help you if you need to complete the documentation or set some CI up.

**Comment by edwin0cheng** [comment]
Currently all lower level crates are lack of documentations, and i think it is good to add back some basic documentation. PR for documentations are always welcome. (As my english not is so good, add back docs are not my priority :) )

On the other hand, i think CI stuffs we could add it later if more ppls are going to contribute. 

And would you mind i add you as the owner for these crates too ? As im quite busy recently. In case you are hurry to push updates on them, you can publish it too.

**Comment by jice-nospam** [comment]
ok no problem, I'll push documentation updates directly here so that you don't have to review merge requests but i'll come back to you before publishing.

**Comment by edwin0cheng** [comment]
Would you mind you still make PR and merge by yourself, It is easier for us to keep tracking :)

**Comment by jice-nospam** [comment]
ok no problem
