### ISSUE TITLE
wasm32: uni-app canvas always resize to entire browser.window ?

### ISSUE THREAD

**Issue by zeroexcuses** [unrust/uni-app#9]
Hi,

  Is there a way in wasm32/uni-app, to ahve the OpenGL canvas always be resized to whatever the size of the browser window is? I tried toggling "fullscreen: true", but that did nothing.

  The goal is:
the browser window displays the uni-app WebGL canvas
the browser window displays nothing but the unik-app WebGL canvas
the WebGL canvas does not overflow

**Comment by edwin0cheng** [comment]
No right now, but currently you can control the canvas in App 
```
pub struct App {
    window: CanvasElement,   /// << this one
    pub events: Rc<RefCell<Vec<AppEvent>>>,
    device_pixel_ratio: f32,
}
```

And using stdweb api to control the size

**Comment by zeroexcuses** [comment]
This worked. Thanks!

For anyone finding this via search, here's what I used:
```
    let window = stdweb::web::window();

    let app = uni_app::App::new(uni_app::AppConfig {
        size: (window.inner_width() as u32, window.inner_height() as u32),
```
